import PublicLayout from "../components/Layouts/public";
import Head from "next/head";
import { supabase } from "../lib/client";

import LatestPosts from "../components/Home/LatestPosts";
export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Home | RCTV Studios</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PublicLayout pageName={"Home"}>
        <main>
          <LatestPosts data={data} />
        </main>
      </PublicLayout>
    </>
  );
}

export async function getStaticProps() {
  const { data, error } = await supabase
    .from("posts")
    .select("id,title,date_published")
    .order("date_published", { ascending: false })
    .limit(2);
  // console.log({ data, error });

  return {
    props: {
      data,
      error,
    },
  };
}
