import PublicLayout from "../components/Layouts/public";
import Head from "next/head";
import { supabase } from "../lib/client";
import Link from "next/link";
export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Home | RCTV Studios</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PublicLayout pageName={"Home"}>
        <main>
          <div>
            <p className="text-xl">Latest Posts</p>
            <div>
              <ul>
                {data.map((post) => (
                  <li key={post.id}>
                    &bull;
                    <Link href={`/post/${post.id}`}>
                      <a className="text-red-500 hover:text-green-500">
                        {post.title}
                      </a>
                    </Link>
                    <p className="text-sm">
                      Published: {""}
                      {new Date(post.date_published).getMonth() + 1}/
                      {new Date(post.date_published).getDate()}/
                      {new Date(post.date_published).getFullYear()}
                    </p>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </main>
      </PublicLayout>
    </>
  );
}
export async function getServerSideProps(context) {
  const { data, error } = await supabase
    .from("posts")
    .select("id,title,date_published")
    .order("date_published", { ascending: false })
    .limit(2);
  // console.log({ data, error });

  return {
    props: {
      data,
      error,
    },
  };
}
